# Generated by Django 4.2.9 on 2024-01-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='images/')),
                ('intro', models.CharField(max_length=1024)),
                ('outro', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamerapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='images/')),
                ('review', models.CharField(max_length=2048)),
                ('main_link', models.URLField(blank=True, max_length=128, null=True)),
                ('amazon_link', models.URLField(blank=True, max_length=128, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamerapp.category')),
            ],
        ),
    ]
