# Generated by Django 4.2.9 on 2024-01-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='review',
            name='outro',
        ),
    ]
