# Generated by Django 4.2.4 on 2024-01-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0003_remove_review_category_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='intro',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
