# Generated by Django 4.2.9 on 2024-01-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0004_review_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='intro',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
