# Generated by Django 4.2.4 on 2024-02-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0007_review_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='main_category',
        ),
    ]
