# Generated by Django 4.2.4 on 2024-03-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0009_sub_subcategory_review_sub_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='path',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
