# Generated by Django 4.2.4 on 2024-03-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0010_sub_category_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_subcategory',
            name='path',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
