# Generated by Django 4.2.4 on 2024-03-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0012_newslettersubscription_delete_affiliateproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
